name: Premake Linux CI

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev \
            libxi-dev libgl1-mesa-dev libglu1-mesa-dev

      - name: Setup Premake
        uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta6"

      - name: Generate GNU Makefiles
        run: |
          cd build
          premake5 gmake2

      - name: Build Release Configuration
        run: make config=release_x64

      - name: Build Debug Configuration
        run: make config=debug_x64
