name: CMake Windows CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build Release Configuration
        run: cmake --build build --config Release

      - name: Build Debug Configuration
        run: cmake --build build --config Debug

      - name: Upload Release Executables
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-executables
          path: |
            build/bin/Release/client.exe
            build/bin/Release/server.exe

      - name: Upload Debug Executables
        uses: actions/upload-artifact@v3
        with:
          name: windows-debug-executables
          path: |
            build/bin/Debug/client.exe
            build/bin/Debug/server.exe
